#include "Header.h"

HWND hwnd;
HWND comboBoxMetalType;
HWND comboBoxItems;
HWND comboBoxArmature;
HWND comboBoxBeamGOST;
HWND comboBoxBeamNormal;
HWND comboBoxBeamWide;
HWND comboBoxBeamColumn;
HWND comboBoxBeamASeries;
HWND comboBoxSquare;
HWND comboBoxCircle;
HWND comboBoxTape;
HWND comboBoxList;
HWND comboBoxCulvertCircle;
HWND comboBoxCulvertProfileSq;
HWND comboBoxCulvertProfileRec;
HWND comboBoxAngle;
HWND comboBoxChannel;

HWND msg;
HWND msg2;
HWND edit;
HWND msgResult;
HWND buttonLengthOrWeight;

void buildGUI()
{
	hwnd = CreateWindow(TEXT("MY_WINDOW"), TEXT("Êàëüêóëÿòîð ìåòàëëà"), WS_OVERLAPPEDWINDOW,
		300, 200, 640, 360, NULL, NULL, NULL, NULL);

	ShowWindow(hwnd, SW_SHOWNORMAL);
	UpdateWindow(hwnd);
	
	comboBoxItems = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VISIBLE | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 10, 270, 300, hwnd, HMENU(IRON::comboBoxID::comboBoxItemsID), NULL, NULL);

	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("àðìàòóðà")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/ÃÎÑÒ 8239-89")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/íîðìàëüíûé(Á)")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/øèðîêîïîëî÷íûé(Ø)")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/êîëîííûé(Ê)")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/äîï.ñåðèè(Ä)")));
	//	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("áàëêà/äâóòàâ/ñâàðíîé(Ñ)")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("êâàäðàò")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("êðóã")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("òðóáà êðóãëàÿ")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("òðóáà ïðîôèëüíàÿ êâàäðàò")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("òðóáà ïðîôèëüíàÿ ïðÿìîóãîëüíèê")));

	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("ëåíòà")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("ëèñò")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("óãîëîê")));
	SendMessage(comboBoxItems, CB_ADDSTRING, 0, LPARAM(TEXT("øâåëëåð")));
	SendMessage(comboBoxItems, CB_SETCURSEL, 0, 0);

	comboBoxMetalType = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VISIBLE | WS_VSCROLL | CBS_DROPDOWNLIST,
		10, 70, 160, 220, hwnd, HMENU(IRON::comboBoxID::comboBoxMetalTypeID), NULL, NULL);

	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("ÑÒ 3")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("10")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("20")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("40X")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("45")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("65")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("65Ã")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("09Ã2Ñ")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("15Õ5Ì")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("10ÕÑÍÄ")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("12Õ1ÌÔ")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("ØÕ15")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ð6Ì5")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó7")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó8")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó8À")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó10")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó10À")));
	SendMessage(comboBoxMetalType, CB_ADDSTRING, 0, LPARAM(TEXT("Ó12À")));
	SendMessage(comboBoxMetalType, CB_SETCURSEL, 0, 0);

	comboBoxArmature = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VISIBLE | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxArmatureID), NULL, NULL);

	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d6  ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d6.5")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d8  ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d10 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d12 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d14 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d16 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d18 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d20 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d22 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d25 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d28 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d32 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d36 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d40 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d45 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d50 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d55 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d60 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d70 ")));
	SendMessage(comboBoxArmature, CB_ADDSTRING, 0, LPARAM(TEXT("d80 ")));
	SendMessage(comboBoxArmature, CB_SETCURSEL, 0, 0);

	comboBoxBeamGOST = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamGOSTID), NULL, NULL);

	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("10")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("12")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("14")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("16")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("18")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("20")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("22")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("24")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("27")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("30")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("33")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("36")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("40")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("45")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("50")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("55")));
	SendMessage(comboBoxBeamGOST, CB_ADDSTRING, 0, LPARAM(TEXT("60")));
	SendMessage(comboBoxBeamGOST, CB_SETCURSEL, 0, 0);

	comboBoxBeamNormal = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamNormalID), NULL, NULL);

	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("10Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("12Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("12Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("14Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("14Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("16Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("16Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("18Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("18Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("20Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("23Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("26Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("26Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("30Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("30Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("35Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("35Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("40Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("40Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("45Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("45Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("50Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("50Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("55Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("55Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("60Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("60Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("70Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("70Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("80Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("80Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("90Á1 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("90Á2 ")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("100Á1")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("100Á2")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("100Á3")));
	SendMessage(comboBoxBeamNormal, CB_ADDSTRING, 0, LPARAM(TEXT("100Á4")));
	SendMessage(comboBoxBeamNormal, CB_SETCURSEL, 0, 0);

	comboBoxBeamWide = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamWideID), NULL, NULL);

	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("20Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("23Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("26Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("26Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("30Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("30Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("30Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("35Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("35Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("35Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("40Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("40Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("40Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("50Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("50Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("50Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("50Ø4")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("60Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("60Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("60Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("60Ø4")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("70Ø1")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("70Ø2")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("70Ø3")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("70Ø4")));
	SendMessage(comboBoxBeamWide, CB_ADDSTRING, 0, LPARAM(TEXT("70Ø5")));
	SendMessage(comboBoxBeamWide, CB_SETCURSEL, 0, 0);

	comboBoxBeamColumn = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamColumnID), NULL, NULL);

	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("20K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("20K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("23K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("23K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("26K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("26K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("26K3")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("30K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("30K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("30K3")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("35K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("35K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("35K3")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("40K1")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("40K2")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("40K3")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("40K4")));
	SendMessage(comboBoxBeamColumn, CB_ADDSTRING, 0, LPARAM(TEXT("40K5")));
	SendMessage(comboBoxBeamColumn, CB_SETCURSEL, 0, 0);

	comboBoxBeamASeries = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamASeriesID), NULL, NULL);

	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("24ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("27ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("36ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("35ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("40ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("45ÄÁ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("45ÄÁ2")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("30ÄØ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("40ÄØ1")));
	SendMessage(comboBoxBeamASeries, CB_ADDSTRING, 0, LPARAM(TEXT("50ÄØ1")));
	SendMessage(comboBoxBeamASeries, CB_SETCURSEL, 0, 0);

	/*comboBoxBeamWeld = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxBeamWeldID), NULL, NULL);

	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("45ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("45ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("45ÁÑ3 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("50ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("50ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("50ÁÑ3 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("50ÁÑ4 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("55ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("55ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ3 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ4 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ5 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("60ÁÑ6 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ3 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ4 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ5 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("70ÁÑ6 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("80ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("80ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("90ÁÑ1 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("90ÁÑ2 ")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("100ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("100ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("100ÁÑ3")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("120ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("120ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("140ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("140ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("140ÁÑ3")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("160ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("160ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("160ÁÑ3")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("160ÁÑ4")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("180ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("180ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("180ÁÑ3")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("180ÁÑ4")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("200ÁÑ1")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("200ÁÑ2")));
	SendMessage(comboBoxBeamWeld, CB_ADDSTRING, 0, LPARAM(TEXT("200ÁÑ3")));
	SendMessage(comboBoxBeamWeld, CB_SETCURSEL, 0, 0);*/

	comboBoxSquare = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxSquareID), NULL, NULL);

	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì3")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì3.2")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì3.5")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì4")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì4.5")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì5")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì5.5")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì6")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì7")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì8")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì9")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì10")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì11")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì12")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì13")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì14")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì15")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì16")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì17")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì18")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì19")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì20")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì21")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì22")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì23")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì24")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì25")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì26")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì27")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì28")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì29")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì30")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì32")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì34")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì35")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì36")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì38")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì40")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì42")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì45")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì46")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì48")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì50")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì52")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì55")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì58")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì60")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì63")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì65")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì70")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì75")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì80")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì85")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì90")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì93")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì95")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì100")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì105")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì110")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì115")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì120")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì125")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì130")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì135")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì140")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì145")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì150")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì160")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì170")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì180")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì190")));
	SendMessage(comboBoxSquare, CB_ADDSTRING, 0, LPARAM(TEXT("ìì200")));
	SendMessage(comboBoxSquare, CB_SETCURSEL, 0, 0);

	comboBoxCircle = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxCircleID), NULL, NULL);

	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d5")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d5.5")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d6")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d6.3")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d6.5")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d7")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d8")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d9")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d10")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d11")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d12")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d13")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d14")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d15")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d16")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d17")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d18")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d19")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d20")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d21")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d22")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d23")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d24")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d25")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d26")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d27")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d28")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d29")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d30")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d31")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d32")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d33")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d34")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d35")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d36")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d37")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d38")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d39")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d40")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d41")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d42")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d43")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d44")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d45")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d46")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d47")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d48")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d50")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d52")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d53")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d54")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d55")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d56")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d58")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d60")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d62")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d63")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d65")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d67")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d68")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d70")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d72")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d73")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d75")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d78")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d80")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d82")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d85")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d87")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d90")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d92")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d95")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d97")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d100")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d105")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d110")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d115")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d120")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d125")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d130")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d135")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d140")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d145")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d150")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d155")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d160")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d165")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d170")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d175")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d180")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d185")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d190")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d195")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d200")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d210")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d220")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d230")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d240")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d250")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d260")));
	SendMessage(comboBoxCircle, CB_ADDSTRING, 0, LPARAM(TEXT("d270")));
	SendMessage(comboBoxCircle, CB_SETCURSEL, 0, 0);

	//comboBoxTape = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
	//	10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxTapeID), NULL, NULL);
	//SendMessage(comboBoxTape, CB_ADDSTRING, 0, LPARAM(TEXT("")));
	//SendMessage(comboBoxTape, CB_SETCURSEL, 0, 0);

	//comboBoxList = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
	//	10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxListID), NULL, NULL);
	//SendMessage(comboBoxList, CB_ADDSTRING, 0, LPARAM(TEXT("")));
	//SendMessage(comboBoxList, CB_SETCURSEL, 0, 0);

	comboBoxCulvertCircle = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxCulvertCircleID), NULL, NULL);

	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)6x10.2x1.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)8x13.5x2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)10x17x2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)15x21.3x2.35")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)15x21.3x2.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)20x26.8x2.35")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)20x26.8x2.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)25x33.5x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)32x42.3x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)40x48x3")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)50x60x3")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)65x75.5x3.3")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)80x88.5x3.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)90x101.3x3.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)100x114x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)125x140x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ë)150x165x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)6x10.2x2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)8x13.5x2.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)10x17x2.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)15x21.3x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)20x26.8x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)25x33.5x3.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)32x42.3x3.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)40x48x3.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)50x60x3.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)65x75.5x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)80x88.5x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)90x101.3x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)100x114x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)125x140x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Î)150x165x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)6x10.2x2.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)8x13.5x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)10x17x2.8")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)15x21.3x3.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)20x26.8x3.2")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)25x33.5x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)32x42.3x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)40x48x4")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)50x60x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)65x75.5x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)80x88.5x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)90x101.3x4.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)100x114x5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)125x140x5.5")));
	SendMessage(comboBoxCulvertCircle, CB_ADDSTRING, 0, LPARAM(TEXT("(Ó)150x165x5.5")));
	SendMessage(comboBoxCulvertCircle, CB_SETCURSEL, 0, 0);

	comboBoxCulvertProfileSq = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxCulvertProfileSqID), NULL, NULL);

	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("10x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("10x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("10x1")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("10x1_2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("10x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x1")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x1_2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("15x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x1")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x1_2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("20x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x1")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x1_2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("25x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x1")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x1_2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x1_3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("30x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("32x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x0_8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x0_9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("35x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("36x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x1_4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x1_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("40x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("42x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("42x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("42x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("42x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("42x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("45x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x4_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("50x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("55x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x2")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x2_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("60x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("65x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("70x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x3_5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x10")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("80x11")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("90x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x3")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x4")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x5")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("100x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("110x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("110x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("110x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("110x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("120x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("120x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("120x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("120x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("140x6")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("140x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("140x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("140x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("150x7")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("150x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("150x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("150x10")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("180x8")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("180x9")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("180x10")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("180x12")));
	SendMessage(comboBoxCulvertProfileSq, CB_ADDSTRING, 0, LPARAM(TEXT("180x14")));
	SendMessage(comboBoxCulvertProfileSq, CB_SETCURSEL, 0, 0);

	comboBoxCulvertProfileRec = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
		10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxCulvertProfileRecID), NULL, NULL);
	
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("15x10x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("15x10x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("15x10x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x10x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x10x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x10x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x10x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x15x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x15x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x15x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x15x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("20x15x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x10x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x10x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x10x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x10x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("25x15x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x10x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x10x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x10x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x10x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x10x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x15x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("30x20x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x15x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x20x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x25x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x25x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x25x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x25x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x25x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("35x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x15x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x15x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x15x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x15x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x15x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x20x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x25x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x20x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x20x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x20x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x20x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x30x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("42x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x20x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x20x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x20x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x20x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x30x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("45x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x25x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x2_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x35x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x40x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x40x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x40x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x40x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("50x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x20x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x25x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x25x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x25x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x25x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x25x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x30x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("60x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x30x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x30x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x30x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x30x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x30x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x40x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x40x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x40x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x50x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x50x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x50x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x60x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x60x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x60x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x60x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("80x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x40x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x40x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x60x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x60x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x60x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x40x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x50x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x50x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x50x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x50x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x60x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x60x3_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x60x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x70x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x70x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x70x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("100x70x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x40x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x40x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x50x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x50x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x50x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x50x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x60x4")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x60x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x60x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("110x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x40x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x40x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x40x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x40x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x60x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x60x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x60x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x80x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x80x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x80x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("120x80x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x60x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x60x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x60x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x80x5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x80x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x80x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x80x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x120x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x120x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x120x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x120x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x80x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x80x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x80x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x80x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x80x10")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x100x6")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x100x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x100x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x100x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x100x1 ")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x80x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x80x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x80x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x80x10")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x80x12")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x100x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x100x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x100x10")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x100x12")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x150x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x150x9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x150x10")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x150x12")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x0_8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x0_9")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x1")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x1_2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("28x25x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x28x1_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x28x2")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("40x28x2_5")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("70x50x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("90x50x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("140x60x3")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("150x60x7")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("160x130x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("180x145x20")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("190x120x12")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("195x170x18")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("200x120x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_ADDSTRING, 0, LPARAM(TEXT("230x100x8")));
	SendMessage(comboBoxCulvertProfileRec, CB_SETCURSEL, 0, 0);

	//comboBoxAngle = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
	//	10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxAngleID), NULL, NULL);
	//SendMessage(comboBoxAngle, CB_ADDSTRING, 0, LPARAM(TEXT("")));
	//SendMessage(comboBoxAngle, CB_SETCURSEL, 0, 0);

	//comboBoxChannel = CreateWindow(TEXT("COMBOBOX"), NULL, WS_CHILD | WS_VSCROLL | CBS_NOINTEGRALHEIGHT | CBS_DROPDOWNLIST,
	//	10, 40, 160, 250, hwnd, HMENU(IRON::comboBoxID::comboBoxChannelID), NULL, NULL);
	//SendMessage(comboBoxChannel, CB_ADDSTRING, 0, LPARAM(TEXT("")));
	//SendMessage(comboBoxChannel, CB_SETCURSEL, 0, 0);

	msg = CreateWindow(TEXT("STATIC"), TEXT("äëèíà â ñì"), WS_CHILD | WS_VISIBLE | ES_CENTER,
		380, 10, 120, 20, hwnd, NULL, NULL, NULL);

	edit = CreateWindow(TEXT("EDIT"), NULL, WS_CHILD | WS_VISIBLE | WS_BORDER | ES_RIGHT | ES_NUMBER,
		380, 40, 120, 20, hwnd, HMENU(IRON::comboBoxID::editID), NULL, NULL);

	msgResult = CreateWindow(TEXT("STATIC"), TEXT("ðåçóëüòàò"), WS_CHILD | WS_VISIBLE | ES_CENTER,
		380, 70, 120, 20, hwnd, NULL, NULL, NULL);

	HWND buttonQuit = CreateWindow(TEXT("BUTTON"), TEXT("âûõîä"), WS_CHILD | WS_VISIBLE,
		510, 10, 90, 20, hwnd, HMENU(IRON::comboBoxID::buttonQuitID), NULL, NULL);

	buttonLengthOrWeight = CreateWindow(TEXT("BUTTON"), TEXT("ñì > êã"), WS_CHILD | WS_VISIBLE,
		295, 10, 75, 20, hwnd, HMENU(IRON::comboBoxID::buttonLengthOrWeightID), NULL, NULL);

	HWND buttonCalculate = CreateWindow(TEXT("BUTTON"), TEXT("ðàñ÷¸ò"), WS_CHILD | WS_VISIBLE,
		510, 40, 90, 20, hwnd, HMENU(IRON::comboBoxID::buttonCalcID), NULL, NULL);

	msg2 = CreateWindow(TEXT("STATIC"), TEXT(""), WS_CHILD | WS_VISIBLE | ES_CENTER,
		380, 100, 120, 20, hwnd, NULL, NULL, NULL);
}